### ISSUE TITLE
Changing the quality of the video

### ISSUE THREAD

**Issue by pat-moreno** [marcoradocchia/youterm#3]
I was able to change the video quality, but note that I don't have "youtube-dl" installed and I use the yt-dlp documentation on Github. After reviewing the code for "__main__.py", I made these changes to line 144. It originally appears like this:
video_fmt = "bestvideo+"
I changed it to:
video_fmt = "[height<=?720]+" 
The "+" is important because line 109 contains the audio/video format to be used:
f"--ytdl-format={video_fmt}bestaudio",
It will use the format you define and (+) the best audio. 
I recommend reading https://github.com/yt-dlp/yt-dlp#filtering-formats, to use the format you like most.

**Comment by marcoradocchia** [comment]
I'm currently working on this.
Exactly as you did, I used the `video_fmt` variable instead of hardcoding it's value in the `mpv` command for a future update where the user will choose the preferred video format himself.
Thanks a lot for opening this issue and for providing such useful information, I appreciate it. I will soon (hopefully tonight/tomorrow) commit the updates, which will also include a config file for `youterm`, and release the new version on PyPi.

**Comment by marcoradocchia** [comment]
`youterm` has been updated to v0.2.0. The update includes the ability to configure the program using a config file and the option to choose the video quality when video option is enabled.
I'm going to close this issue, but if you have any other suggestions or you enconter any bugs let me know!
